name: Deploy_to_my_VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check what is inside
        run: ls -al

      - name: Get content for repo
        uses: actions/checkout@v4

      - name: Check after repo is here
        run: ls -al
      - name: install sshpass
        run: sudo apt-get install -y sshpass
      - name: archive all project files
        run: |
          tar --exclude='/.git' --exclude='/.github' -czvf app_code.tar.gz .
      #- name: connect to VM
       # uses: shimataro/ssh-key-action@v2
        #with:
         # key: ${{ secrets.MY_SECRET_KEY }}
          #known_hosts: '192.168.110.116'

      - name: Deploy to VM
        run: |
          sshpass -p ${{ secrets.VM_PASSWORD }} ssh -o StrictHostKeyChecking=no -p 13371 ${{ secrets.VM_USER }}@0.tcp.eu.ngrok.io "
          echo 'moving to work dir' &&
          cd /var/www/web_site &&
          echo 'directory content' &&
          ls -al && 
          echo 'directory is' &&
          pwd"
