name: Deploy_to_my_VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check what is inside
        run: ls -al

      - name: Get content for repo
        uses: actions/checkout@v4

      - name: Check after repo is here
        run: ls -al
