name: Deploy_to_my_VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check what is inside
        run: ls -al

      - name: Get content for repo
        uses: actions/checkout@v4

      - name: Check after repo is here
        run: ls -al

      - name: connect to VM
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.MY_SECRET_KEY }}
          known_hosts: '192.168.110.116'

      - name: Deploy to VM
        run: |
          ssh -o StrictHostKeyChecking=no github_actions@192.168.110.116 "
          cd /var/www/web_site & ls -al"
