name: Deploy_to_my_VM
env:
  WORK_DIR : "/var/www/web-site"
  VM_IP    : "0.tcp.eu.ngrok.io"
  VM_PORT  : "13371"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check what is inside
        run: ls -al

      - name: Get content for repo
        uses: actions/checkout@v4

      - name: Check after repo is here
        run: ls -al
      - name: Remove unnessasy folders
        run: rm -r ./.git ./.github
      - name: install sshpass
        run: sudo apt-get install -y sshpass
      - name: archive all project files
        run: zip -r app_code.tar.gz ./ -x *.git*


      - name: Deploy to VM
        run: |
          sshpass -p ${{ secrets.VM_PASSWORD }} scp -o StrictHostKeyChecking=no -P 22 app_code.tar.gz ${{ secrets.VM_USER }}@${{ env.VM_IP }}:${{ env.WORK_DIR }}

      - name: check files are there
        run: |
          sshpass -p ${{ secrets.VM_PASSWORD }} ssh -o StrictHostKeyChecking=no -p ${{ env.VM_PORT }} ${{ secrets.VM_USER }}@${{ env.VM_IP }} "
          echo 'moving to work dir' &&
          cd ${{ env.WORK_DIR }} &&
          echo 'directory content' &&
          ls -al && 
          echo 'directory is' &&
          pwd"
